### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by evanharmon** [laurelherting/portfolio#83]
Eslint / prettier should be working now. I would create a feature branch `fix/linting-errors` and fix these errors then PR. I like to keep these types of fixes apart from new features / changes.

React and Nodejs projects have started using a combo of eslint and prettier across the board. With the prettier plugin for our editors, all our code looks the same and has a standard. It makes code reviews and stepping in to other repos MUCH easier. :)

Some examples from `App.js`:
Component isn't used since you're using a stateless component - this should just be an import for react
```
import React, { Component } from 'react';
```

indenting
```
const App = () => (
<Router>
    <div>
        <header id="home" className="height: 753px;">
...
```

**Comment by laurelherting** [comment]
Okay, thank you. This makes sense.
